# @package _global_

# specify here default preprocessing configuration
defaults:
    # can be any config file in the preprocessing_pipeline folder
    - preprocessing_pipeline: decision_tree.yaml


# You might add another configurations: which model to use, which visualizations, etc.
# See also: https://medium.com/pytorch/hydra-a-fresh-look-at-configuration-for-machine-learning-projects-50583186b710
print_config: True

